language: python
sudo: required
dist: xenial

python:
- '3.7'
- '3.8'
- '3.9'

install:
- pip install .
- pip install pytest pytest-cov coveralls

script:
- pytest --cov=urdfpy tests

after_success:
- coveralls || true
